### ISSUE TITLE
Please report the problems about data missing under this issue. 请在此issue下反馈数据丢失的问题。

### ISSUE THREAD

**Issue by Septentrion** [cnwangjie/better-onetab#121] opened 2019-02-15 13:00 UTC
扩展版本 (extension version): 1.3.12
浏览器版本 (browser version): Firefox 66
操作系统 (operating system): macOS HighSierra
问题描述 (problem description): 
 
Hello
I just opened my browser this morning... and discover that all the pages I had stored In the extension had vanished :o(
I was a bit angry because there was some important resources I was working on.
I did not do anythng specific (as far as I'm conscious of...)

Too bad, because I enjoyed using better-onetab (but “better” ?? ;o| )

**Comment by cnwangjie** [comment] 2019-02-16 10:32
Hi, I'm sorry about this. Better OneTab will add links to browser history when you store them by default. You could try to find them in your browser history. Hope this could help you.

**Comment by rasenplanscher** [comment] 2019-03-20 10:59
This happened to me today when Firefox updated.
I even just saved my whole session in better-onetab, just to be sure 🤡😭

> Better OneTab will add links to browser history when you store them
Now, I finally see the value in that, although it's still a pain with older tabs...

**Comment by rasenplanscher** [comment] 2019-03-20 10:59
@cnwangjie 
Where does the extension store its data? Maybe it can be restored 🤔

**Comment by cnwangjie** [comment] 2019-05-02 09:06
Hi, I spent some time to try to fix this problem. I can not reproduce it in a long time but still many people report this problem. So a try to check many resources and try to solve it. 

I found it will be caused by a JS concurrency problem.

There is an article describe it here: https://balpha.de/2012/03/javascript-concurrency-and-locking-the-html5-localstorage/

I reference some solution and reviewed my code and try to avoid accessing storage concurrently.

> https://stackoverflow.com/questions/124764/are-mutexes-needed-in-javascript
> https://developer.mozilla.org/en-US/docs/Web/API/Web_Locks_API

And I released a new version with the patch maybe fix this problem. Could you update the extension to the latest version (1.4.4) and check it and send me any feedback? I'm not sure whether it won't appear so I plan to keep this issue open.

Please talk about the similar problem about data missing under this issue. Thank you.

**Comment by cnwangjie** [comment] 2019-05-02 09:21
Besides, the data of the extension is not stored in plain text. It has a different implementation in a different browser (chromium use leveldb). So it is hard to restore data from local storage files (I'm not sure whether it is possible). If you want to find the missing data please try to find it from the browser history. I'm very sorry for your lost.

refer: https://github.com/cnwangjie/better-onetab/issues/115#issuecomment-463187618

@rasenplanscher

**Comment by jaccarmac** [comment] 2019-05-04 07:04
I have 1.4.4 installed in both Chrome and Firefox. Chrome works fine. FIrefox has stopped saving new tabs or deleting opened ones this week. They disappear from the list but come back (or disappear) when I restart the browser. Seems like a race is likely (the other difference between Chrome and FF is that FF doesn't load in dark mode, I have to restart for that to work.)

**Comment by cnwangjie** [comment] 2019-05-04 09:01
@jaccarmac Thank you for reports. Did you mean Firefox cannot close tabs and save them? Or it closes the tabs but not appear in tab list?

Besides, could you successfully install the new version in Firefox? I received an email said he cannot install the new version because the new version cannot be verified. I confirmed it in my Firefox 66.0.3 with the same case.

**Comment by jaccarmac** [comment] 2019-05-04 16:36
They appear in the list but after the browser is closed the list reverts to its old state. It seems to have something to do with the code which is trying to persist the list, and I can't see any errors in console while the extension is open.

The Firefox issue is because [Mozilla let a cert expire, which is breaking all add-ons](https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/). My copy doesn't have their hotfix yet, I'll let you know when I can update add-ons again.

**Comment by jaccarmac** [comment] 2019-05-05 06:15
Quick update: I've just realized that reloading the page also restores the tab lists to their previous state.

**Comment by liaodongd** [comment] 2019-05-13 09:14
扩展版本 (extension version): 1.4.5
浏览器版本 (browser version): 65.0.3325.146（正式版本） （32 位）
操作系统 (operating system): WIN7
问题描述 (problem description):
 import datas from OneTab, close 'better onetab' tab, when i click it in extension button,all the data has disappeared!
从OneTab导入的标签,关闭'better onetab'标签页,再点击扩展程序的'better onetab'按钮前面导入的url都没了

**Comment by liaodongd** [comment] 2019-05-13 09:31
Open chrome dev-tool(F12) - Application-Storage and Cache is empty even if I add a new tab
打开谷歌浏览器F12在application中storage和cache都是空的 哪怕我新增一个标签
i see oneTab data is save in Storage-Local Storage-chrome-extension://${oneTab Id}
我看oneTab数据是存在本地的local-storage

**Comment by prunepasty** [comment] 2019-05-31 13:59
So if you have lost all your tabs in Better-onetab with Firefox. There is no way to recover them?

(Except using the history in Firefox).

**Comment by jaccarmac** [comment] 2019-05-31 17:30
The only way I found was using the history, unfortunately. I didn't end up diving into the code but it appeared that the extension was closing before it could write any data about the tabs to disk.

**Comment by RaphBenYisrael** [comment] 2019-06-04 03:10
ALL OF MY TABS MIRACOUSLY CAME BACK ON THERE OWN! I JUST CHANGED MY REVIEW TO 5 STARS ON THE WEB STORE! I'M BACKING UP THIS TIME JUST IN CASE! BUT IM VERY HAPPY AND RELIEVED! HOPEFULLY OTHERS TABS ARE BACK TOO!

**Comment by prunepasty** [comment] 2019-06-04 11:12
> 
> 
> ALL OF MY TABS MIRACOUSLY CAME BACK ON THERE OWN! I JUST CHANGED MY REVIEW TO 5 STARS ON THE WEB STORE! I'M BACKING UP THIS TIME JUST IN CASE! BUT IM VERY HAPPY AND RELIEVED! HOPEFULLY OTHERS TABS ARE BACK TOO!

Good for you. However, the same has not happened for me. All my Better-onetab tabs have disappeared, never to return. I first used Better-onetab, as a substitute for OneTab, when OneTab developed an issue. It would not save YouTube tabs for some reason. However, this problem has now been fixed. So, although Better-onetab was a good add-on, I have gone back to using OneTab.

**Comment by RaphBenYisrael** [comment] 2019-06-05 17:14
> > ALL OF MY TABS MIRACOUSLY CAME BACK ON THERE OWN! I JUST CHANGED MY REVIEW TO 5 STARS ON THE WEB STORE! I'M BACKING UP THIS TIME JUST IN CASE! BUT IM VERY HAPPY AND RELIEVED! HOPEFULLY OTHERS TABS ARE BACK TOO!
> 
> Good for you. However, the same has not happened for me. All my Better-onetab tabs have disappeared, never to return. I first used Better-onetab, as a substitute for OneTab, when OneTab developed an issue. It would not save YouTube tabs for some reason. However, this problem has now been fixed. So, although Better-onetab was a good add-on, I have gone back to using OneTab.

Yeah, maybe it was just a fluke on my end. Not sure. Also, just realized my tabs weren't restored 100%, but only up until a month ago, 4/21/19 to be exact. But I'll take that! Anyway, I had been messing with the sync option for a couple of days. Just constantly trying to sync over and again, and seemingly nothing was happening. It was my hope that it would possibly restore some tabs, and supposedly it did eventually. Again, not quite sure how I got so many tabs/groups restored, but not complaining. Sorry if I got anybody's hopes up. I initially assumed that an update restored them.

**Comment by cnwangjie** [comment] 2019-08-08 07:55
Hi, all. I've published a new version to try to fix this problem. It seems caused by the storage lock won't be unlocked. I tried to avoid this problem in the new version. If this problem still exists, please submit a new issue.

**Closed by cnwangjie** 2019-08-08 07:55 UTC
Labels: bug, firefox

**Comment by succeedmr123** [comment] 2019-11-08 23:55
Man, this is verified.
in two occasions, better -onetab was flaky and un-relčiable in the following way:

-it closed e.g. 74 tabs
-these tabs do not get written into better-onetab database.

will not write versions and nothing, as its all up to date as of this date of writing, all 64-bit.

Best,

**Comment by BSDxxxx** [comment] 2019-12-27 02:12
It still happens occasionally in Version: 1.4.7,  could the reason be my chrome settings--仅将本地数据保留到您退出浏览器为止?
