### ISSUE TITLE
Poor UI performance with a large number of lists and tabs 列表较多时UI性能严重下降

### ISSUE THREAD

**Issue by onefork** [cnwangjie/better-onetab#55] opened 2018-10-09 14:01 UTC
扩展版本 (extension version): 1.3.10
浏览器版本 (browser version): 69.0.3497.100 (Official Build) (64-bit)
操作系统 (operating system): Windows 10 Version 1803

问题描述 (problem description): 
The tab list detail page has some UI performance issue as the saved lists grows (e.g. 2k+ tabs saved in 200+ lists).
当保存的页面较多时（如200+列表，2000+地址），网页列表信息页UI性能下降很厉害。

实际行为 (actual behavior): 
All UI elements on the tab list detail page are laggy.
网页列表信息页上全部UI元素都出现卡顿。

期望行为 (expected behavior): 
Better UI performance.
优化UI性能。

重现步骤 (reproduce step):
1. Add 200+ lists with 10 tabs each, 2k+ tabs in total;
2. Open tab list detail page;
3. All UI elements on this page are laggy.

1. 添加200+列表，每个10个地址，共2000+地址；
2. 打开网页列表信息页；
3. 页面上全部UI元素都出现卡顿。

**Comment by roscopecoltran** [comment] 2018-10-12 08:02
Hi guys,

Hope you are all well !

I am having the same issue about performances but also for searching my bookmarks. Would be great to create a fork for better-ontab using golang/gopherjs so we could use local embedded data stores like boltdb, cayley (graphdb) or bleve, and add a local api-server with new features managing large scale lists (also we can abstract those lists with a [taggraph](https://github.com/ckaznocha/taggraph)... 

More over, one of my current problem, is that I bookmarked lots of github repo url, thought to fork better-onetab to add some custom rules, like adding github topics for each link saved or extracting some opengraph meta-data, but without a proper backend api, the performance issue will remain as the bottleneck.

Are those features, related to large list, something in the scope of better-onetab ? Is it too advanced/complex ? Would be great to have the project's owner point of view ^^

Cheers,
Rosco

**Comment by cnwangjie** [comment] 2018-10-12 09:29
@roscopecoltran Hi, I think the current problem of performance this issue mentioned is due to a lot of DOM operations. Other possible performance issues stem from data read and write.

I think if you want to build your large data repository you should not rely entirely on the browser. Maybe you could look for or build a backend service to help you make the job you want.

**Comment by onefork** [comment] 2018-10-12 15:54
@cnwangjie Thanks for the explanation and this great addon.

At the moment every element on the page (e.g. menu bar) is influenced by the performance issue.
I'm not familiar with Vue at all. But I could imagine I would be cumbersome to fix the performance bottlenecks.

Here are my primitive ideas on possible workarounds:

1. If the number of urls or lists exceeds a limit, show all lists collapsed by default, with only the list title and favicons in one row as a preview. Once the user click a list, expand the list and render the urls in it on demand. 

2. The functionality to group lists and to only show the lists of the selected group would also be great.

Best

**Comment by HopeForToday** [comment] 2018-12-15 12:50
Same to me, BOT is not as good as original OneTab in performance with many tab lists.

System infos:

- Manjaro 18.0.0
- Vivaldi 2.0.1309.29
- BetterOneTab 1.3.11

**Comment by cnwangjie** [comment] 2019-01-29 12:51
Hi, guys.

The new version (1.4.0) was released today. The lists will be paginated to display if they are too many. And I reduced the times to write data. I noticed too much data will spend a lot of time when IO. Write ~200 lists and ~2k tabs will spend several hundred milliseconds in my nvme disk. So I am not very support store too much data. large amounts of data IO will inevitably cause performance impact.

Previously it almost never work when the label exceeded 500 when I test. However it is available now although the performance is still not good. I will try further optimization later. For example, try not to read and write all data at once.

The current version may still have problems. It is very welcome to provide further reports after test. This issue will remain open status.

Thank you very much.

**Comment by onefork** [comment] 2019-01-31 16:08
Thank you a lot for the effort. I managed to import 2000+ tabs and the performance is much better now. There seem to be some issues when I tried to sync those tabs.

There's also a bug which causes the tab list to show only 9 of the many tab groups I have. However I can access them from the simple list.

**Comment by cnwangjie** [comment] 2019-02-01 03:39
@onefork Hi, it looks a serious bug if you have many lists but show only 9.

Lists will be displayed in pagination and default 10 lists in one page. Is there a paging button on your page? The current display error is usually caused by a data format error.

I added a function to filter data in the wrong format when the extension was started. Could you try to relaunch extension? And look how about it. Hope you can provide more information if it is still cannot display list correctly.

Thank you.

**Comment by onefork** [comment] 2019-03-31 14:48
@cnwangjie thank you. The tab group issue was my mistake. It actually works as expected.

**Comment by vRobM** [comment] 2019-05-31 19:01
I just tried to BOT 1200 tabs and it was a horrible experience that took 20m to resolve since FF was very laggy and unresponsive.

Perhaps changing the way things are being done in groups of 10-20 at a time instead of all at once?

**Comment by cnwangjie** [comment] 2019-08-08 08:05
> I just tried to BOT 1200 tabs and it was a horrible experience that took 20m to resolve since FF was very laggy and unresponsive.
> 
> Perhaps changing the way things are being done in groups of 10-20 at a time instead of all at once?

@vRobM Hi, did you try to store or restore 1200tabs at the same time or import 1200 tabs? I think it is no problem to import 1200 tabs now. But it is unimaginable that open 1200 tabs at the same time in the browser.

**Comment by cnwangjie** [comment] 2019-08-08 08:07
This issue has not been mentioned for a long time. I'll close this issue firstly. But if there still are some problems with it, it is welcome to reopen this issue.

**Closed by cnwangjie** 2019-08-08 08:07 UTC
Labels: performance

**Comment by vRobM** [comment] 2019-08-08 20:01
It is bad form to ask a question and then close the issue.

You did not address the many tabs all at once problem.
You did not consider implementing 10-20 tab actions at a time to minimize
browser stress.
What changes were made? Did you have test results?

Best,

++ Rob

About me <https://remote.com/r>

**Comment by cnwangjie** [comment] 2019-08-09 02:56
@vRobM Obviously I tried to operate 20+ tabs at the same time. It is normal for me. And it is the original intention for me to develop this extension. But it causes browser stress is very normal. I have no way to solve the performance problem of the browser. What I can do is just call the browser API. If you think it'll cause bad performance when operating too many tabs, you can manually select 10-20 tabs in a group.

Thank you for your attention to this problem in a long time. If you have a detail solution for this problem it is very welcome to talk about it or submit a PR to solve this directly. This issue is mainly for the UI performance instead of the performance on the action with too many tabs. You can open a new issue for your problem. :)

**Comment by vRobM** [comment] 2019-08-09 03:02
Thank you for your response.

I may have other issues affecting performance, which also causes UI
performance issues.

You may close the issue.

++ Rob

About me <https://remote.com/r>

**Comment by nyanpasu64** [comment] 2020-04-18 08:39
> This issue is mainly for the UI performance instead of the performance on the action with too many tabs.

I've used better onetab on Firefox for months to years. The more tabs you have, the slower the page gets. Dragging the scrollbar quickly around the page causes the page to spend 0.5-2 seconds frozen rerendering.

![better onetab slow](https://user-images.githubusercontent.com/913957/79632581-23044480-8115-11ea-92fc-5dc5c852f25f.png)

**Comment by MarsZone** [comment] 2020-06-08 03:34
BUG Fix 
https://github.com/cnwangjie/better-onetab/pull/302
This is not a problem any longer.
